libAthena/athena

- include/Athena/FileReader.hpp
- include/Athena/FileWriter.hpp
- include/Athena/Global.hpp
- include/Athena/IStreamReader.hpp
- include/Athena/IStreamWriter.hpp
- include/Athena/MemoryReader.hpp
- include/Athena/MemoryWriter.hpp
- src/Athena/FileReader.cpp
- src/Athena/MemoryReader.cpp
* Streamed reading into pre-allocated buffers
* `IStreamReader::seekAlign32` method
* Small implementations made header-only and inlined
* `ROUND_UP_32` and `ROUND_UP_16` macros
> lots of new streaming interface additions

- src/athena/DNAYaml.cpp
Performs some minor cleanup related to the existing code. Notably, it gets rid of a file-scope static constructor that would have had to execute on program start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/41)
> DNAYaml: Minor cleanup

- include/athena/IStreamReader.hpp
- include/athena/IStreamWriter.hpp
We can simply use std::make_unique instead of raw new + memset. For fill(), we can just use std::vector, given one of its constructors allows for an initial value to be specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/44)
> IStreamReader/IStreamWriter: Simplify buffer functions where applicable

- include/athena/Global.hpp
- src/athena/Global.cpp
`<iostream>` injects a static constructor into every translation unit that includes the header⁠—even if [nothing](https://godbolt.org/z/bXCJMf) from the header is used. This can result in minor initial program slowdown, as all of these constructors need to run before main() can execute.
Instead, we can use `<ostream>`, which includes all of the necessary machinery that we need, placing the `<iostream>` instance into the cpp file, preventing it from propagating across translation units.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/47)
> Global: Change <iostream> include into <ostream>

- include/LZ77/LZBase.hpp
- include/LZ77/LZLookupTable.hpp
- src/LZ77/LZBase.cpp
- src/LZ77/LZLookupTable.cpp
Minor cleanup related to the LZBase and LZLookupTable classes. Which are mainly related to const correctness, modernizing some aspects and removing unused headers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/48)
> LZBase/LZLookupTable: Minor cleanup

- atdna/main.cpp
Reduces the amount of overall allocation churn due to string concatenation by avoiding redundant string temporaries.
While we're at it, we can also clean up shadowed variable warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/56)
> atdna/main: Avoid unnecessary string churn

- include/athena/MemoryWriter.hpp
Makes the variable initialization behavior deterministic in the case of the default constructor. This also eliminates the possibility of an uninitialized read from occurring within the destructor entirely; even in the face of future changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/57)
> MemoryWriter: Initialize member variables to deterministic values

- src/athena/MemoryWriter.cpp
Prevents potential leaks within failure cases in error cases (e.g. in the event of the non-throwing default exception handler).
While we're at it, we can also make some cleanups here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/58)
> MemoryWriter: Prevent potential leak within save()

- src/LZ77/LZType10.cpp
- src/LZ77/LZType11.cpp
- src/athena/Compression.cpp
There's no need to cast here in a few of these areas, so we can remove them.
This also resolves quite a few -Wcast-qual warnings,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/59)
> Compression/LZ77: Remove unnecessary pointer casts

- src/athena/Checksums.cpp
This should be checking if the input is null rather than not null before early exiting, otherwise the data itself will never have the checksum calculated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/60)
> Checksums: Correct null check within crc16()

- src/athena/FileWriterWin32.cpp
Handles the case where a given size exceeds the maximum value that can be contained within a DWORD. Given a DWORD is 32-bit in size and an atUint64 is 64-bits in size, this avoids errors on valid sizes, even if they're extremely unlikely to ever occur.
Makes the file support even with the Unix one (which is able to handle >4GB file writing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/61)
> FileWriterWin32: Handle large files within writeUBytes

- CMakeLists.txt
- src/athena/FileWriterWin32.cpp
- src/athena/MemoryReader.cpp
Avoids needing to explicitly define these in code and also allow external targets to be unaffected by this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/63)
> CMakeLists: Define -DNOMINMAX and -DWIN32_LEAN_AND_MEAN on Windows

- include/athena/Global.hpp
While we're at it, we can also make them noexcept
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/64)
> Global: Make operator|= and &= for enums constexpr

- atdna/test.hpp
- include/athena/DNAOp.hpp
- include/athena/DNAYaml.hpp
- include/athena/Utility.hpp
Allows this code to still function if the enums are turned into enum classes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/66)
> General: Be explicit about SeekOrigin and Endian types

- atdna/main.cpp
- include/athena/Global.hpp
Makes the enumeration strongly typed and also allows forward declaring the enumeration type as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/67)
> Global: Make SeekOrigin an enum class

- include/athena/Global.hpp
- include/athena/IStream.hpp
- include/athena/IStreamReader.hpp
- include/athena/IStreamWriter.hpp
Makes the type strongly-typed and not susceptible to implicit conversions. This also makes it more straightforward to migrate over to `std::endian` whenever that facility is available, given it's also an enum class. Given everything else has been migrated over to the qualified name of the enum values, this shouldn't break compilation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/68)
> General: Make Endian an enum class

- include/athena/DNAYaml.hpp
- src/athena/DNAYaml.cpp
We can collapse two functions into a single function and also make use of it in `NodeToVec()`, where a constexpr boolean is tested against.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/72)
> DNAYaml: Make use of if constexpr where applicable

- atdna/test.cpp
- include/athena/Global.hpp
Given the use of fmt, we can trivially remove the remaining usages of this define and remove it from the Global header. Even without fmt, MSVC has supported the use of `%zu` since C++11 support was added to the compiler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/71)
> Global: Remove compatibility formatting define for size_t 

- include/athena/IStream.hpp
The proper prototype and implementation lies within Global.cpp/.hpp, which takes a const reference rather than a non-const reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/70)
> IStream: Remove unimplemented operator<< prototype

- include/athena/IStreamWriter.hpp
We can leverage writeBytes as opposed to writeUBytes to eliminate all but one cast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/libathena/athena/69)
> IStreamWriter: Eliminate several casts
